# Generated by Django 4.1.4 on 2023-01-22 12:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('mobile_num', models.PositiveIntegerField()),
            ],
        ),
    ]
