# Generated by Django 4.1.4 on 2023-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_lastname_alter_student_mobile_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_num',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
