# Generated by Django 4.1.4 on 2023-01-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
