# Generated by Django 4.1.4 on 2023-01-22 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_student_first_name_remove_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
    ]
