# Generated by Django 4.1.4 on 2023-01-24 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2023, 1, 24)),
        ),
    ]
