# Generated by Django 4.1.4 on 2023-01-24 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_created_by_student_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 1, 24)),
        ),
    ]
